add faq title, lint styles, format code
MailCheck-co/mailcheck.site pull request #376
Opened 2021-07-27 12:16 UTC by mefistofelus

2021-07-28 04:08 UTC, imhul requested changes

2021-07-28 04:08 UTC, imhul commented on src/lib/Article/layout.svelte
> +  schemas={[websiteSchema, articleSchema]} />
Н странице FAQ нам не нужна схема articleSchema

2021-07-28 04:08 UTC, imhul commented on src/lib/Article/layout.svelte
> +{#if slug == 'faq'}
Не вижу смысла объединять два лайаута в один

2021-07-28 04:08 UTC, imhul commented on src/lib/Article/layout.svelte
> +  export let noindex = false;
Тут должна быть подключена анимация дропдаунов FAQ

2021-07-28 13:09 UTC, imhul requested changes
На главной странице не виден компонент Progress, соответственно она загружается с ошибкой

2021-07-28 13:09 UTC, imhul commented on src/lib/MdLayouts/FaqLayout/FaqLayout.svelte
> +    new custom layout faq
Это не стоит оставлять

2021-07-29 06:55 UTC, imhul approved these changes

2021-07-29 08:38 UTC, nosovk commented on src/routes/faq/index.md
> +   2.100 emails if your card details were provided (we don't charge you anything unless you previously has chosen a plan)
тут забыт разделитель

2021-07-29 08:39 UTC, nosovk commented on src/routes/faq/index.md
> +   1.10 emails if you didn't set your card
тут забыт разделитель

2021-07-29 08:40 UTC, nosovk commented on src/routes/faq/index.md
> +1. **Step 1** If you have data collected in .csv, .tsv formats, feel free to click "Upload"
был ранее буллет список, с цифрами будет тафтология
1. шаг 1
с булетами было лучше, вернуть буллет не можем?

2021-07-29 08:40 UTC, nosovk commented on src/routes/faq/index.md
> +-with card 100 emails
забыт пробел разделитель

2021-07-29 08:43 UTC, imhul commented on src/routes/faq/index.md
> +1. **Step 1** If you have data collected in .csv, .tsv formats, feel free to click "Upload"
В тех местах, где **Step 1**, с буллетами текст получается запутанный. Так намного понятнее смотрится

2021-07-29 09:25 UTC, imhul approved these changes

2021-07-30 09:17 UTC, nosovk commented on src/routes/faq/index.md
> +1. **Step 1** If you have data collected in .csv, .tsv formats, feel free to click "Upload"
тогда уточнить у @fredmoss , как скажет так и сделаем

2021-08-06 08:06 UTC, merged